### ISSUE TITLE
Printed hash on `public` is not the same as the one that a user gets a url to

### ISSUE THREAD

**Issue by daviddias** [diasdavid/ipscend#108]
On a `ipscend publish`
```
  { path: 'public',
    hash: 'Qmd6DAJkSKDLV8HYodQeTxkH5JywxmUjG4TPwAa8MF2TkF',
    size: 735894 } ]
Published public with the following hash: QmezL5kwYHSL1vaKRhs1Ugxq9pCPTJU3PiKEvjTu6utSNm
You can access it through your local node or through a public IPFS gateway:
http://localhost:8080/ipfs/QmezL5kwYHSL1vaKRhs1Ugxq9pCPTJU3PiKEvjTu6utSNm
http://ipfs.io/ipfs/QmezL5kwYHSL1vaKRhs1Ugxq9pCPTJU3PiKEvjTu6utSNm
```

**Comment by olizilla** [comment]
Also of note, the `ipscend.json` looks like this:

```json
{
  "versions": [
    {
      "hash": "QmezL5kwYHSL1vaKRhs1Ugxq9pCPTJU3PiKEvjTu6utSNm",
      "timestamp": "2017-05-25T12:15:58.942Z"
    }
  ],
  "path": "public"
}
```

**Comment by enricomarino** [comment]
PR [#89](https://github.com/diasdavid/ipscend/pull/89) should fix it

**Comment by andriytyurnikov** [comment]
any updates on this one?

**Comment by david4096** [comment]
Also experiencing this problem, had to go look at the paths to find the actual hash that would resolve properly on ipfs.io.

https://ipfs.io/ipfs/QmUsfqmcXvAPk9UE2h9FfNDLNEyztMVAcRbfsWMeggtv2g was in ipscend.json as the most recent publish which points to a directory off the path.

The hashes printed to stdout from `ipscend publish` were more useful.

https://ipfs.io/ipfs/QmVas4TF6xYaMpUr3Qcc13bkocTm67NCbYHLd3T6i9pHPG .

**Comment by daviddias** [comment]
Hi @andriytyurnikov, @david4096, @enricomarino! I'm no longer maintaining this module. The good news is that there is one way better on the block, check the deprecation notice -- https://github.com/ipfs-shipyard/ipscend/blob/master/README.md#deprecation-notice -- to find a url to it and a tutorial on how to use it!
