### ISSUE TITLE
Can I have the ipsurge npm package?

### ISSUE THREAD

**Issue by fiatjaf** [diasdavid/ipscend#111]
I'm developing a competitor to ipscend which is obviously destined to fail since ipscend has much more glamour... -- ok, it's better to say I'm developing a program **inspired by ipscend** at https://github.com/fiatjaf/ipsurge and I've noticed the npm package `ipsurge` is abandoned and pointing to this repository. Is there a chance you'll give it to me or should I start thinking about a different name?

Thanks!

**Comment by daviddias** [comment]
Hi @fiatjaf! Thanks for reaching out. As you might have noticed, I've had little time to devote to ipscend/ipsurge but the dream and desire to make it a super useful tool remains.

Would you like to join forces and build a awesome project for the IPFS community and help everyone publish their websites to the DWeb?

**Comment by fiatjaf** [comment]
Of course I would like to join forces, but joining forces is sometimes too complicated in comparison with just developing stuff by myself... What do you propose?

My ipsurge does these things differently from ipscend:

  1. It allows for files to be ignored using a gitignore-like file;
  2. It manages keys and publishes hashes to `/ipns` automatically;
  3. It allows for a quick visualization of the site on `/ipfs` before publishing to `/ipns`;
  4. It doesn't have the screenshot stuff, which although nice adds too much overhead to a tool that should be small and simple.

**Comment by fiatjaf** [comment]
Actually, I think these efforts can be abandoned as it is better and easier to just use MFS for all your IPFS site needs.
