### ISSUE TITLE
Publish each webpage on its own subdomain

### ISSUE THREAD

**Issue by daviddias** [diasdavid/ipscend#113]
Let each page exist on a `base32CIDV1`.ipfs.io

**Comment by ghost** [comment]
Related: https://github.com/ipfs/in-web-browsers/issues/89

tl;dr `cidv1b32.ipfs.somedomain.com`

**Comment by ghost** [comment]
~~Wrong related link, should have been https://github.com/ipfs/in-web-browsers/issues/89~~
