### ISSUE TITLE
Cannot publish

### ISSUE THREAD

**Issue by MrToph** [diasdavid/ipscend#116]
Hi,
I run go-ipfs with `ipfs daemon` and it starts successfully with `API server listening on /ip4/127.0.0.1/tcp/5001`.

So the host:port seems correct to me.
When I run `ipscend publish` now it is stuck and doesn't do anything. No log is shown.

Is it only me or does this tool not work anymore?

**Comment by raucao** [comment]
Same here. No output, just hangs.

**Comment by daviddias** [comment]
Hi @MrToph, @skddc! I'm no longer maintaining this module. The good news is that there is one way better on the block, check the deprecation notice -- https://github.com/ipfs-shipyard/ipscend/blob/master/README.md#deprecation-notice -- to find a url to it and a tutorial on how to use it!

**Comment by MrToph** [comment]
Yes, heard about that one. Thanks, closing.
